import { Locale } from "../../settings/utils/Locale";

const QUESTIONS_KO: string[] = [
  // #처음 만난 순간 (5)
  "{{name}}와(과) 처음 만났던 날, 우리는 어떻게 가족이 되었나요?",
  "{{name}} 이름의 뜻은 무엇인가요?",
  "처음 집에 왔을 때, {{name}}은(는) 어떤 모습을 보였나요?",
  "처음 함께했던 밤, {{name}}은(는) 어디에서 잠들었나요?",
  "{{name}}을(를) 처음 씻겼을 때, 어떤 반응을 보였나요?",

  // #함께했던 일상 (14)
  "아침에 일어났을 때, {{name}}은(는) 보통 무엇을 하고 있었나요?",
  "외출했다 돌아왔을 때, {{name}}의 반응은 보통 어땠나요?",
  "{{name}}이(가) 가장 좋아했던 장소는 어디였나요?",
  "{{name}}이(가) 가장 좋아했던 장난감이나 놀이는 무엇인가요?",
  "{{name}}은(는) 어떤 간식을 제일 좋아했나요?",
  "{{name}}이(가) 나를 놀라게 했던 순간이 있었나요?",
  "{{name}} 때문에 너무나 웃겼던 순간이 있나요?",
  "{{name}}이(가) 사고를 쳐서 난감했던 순간이 있었나요?",
  "{{name}}이(가) 나에게 예상치 못한 감동을 준 순간이 있었나요?",
  "{{name}}이(가) 좋아했던 주변인이나 캐릭터가 있다면 소개해주세요!",
  "맛있는 간식이 먹고 싶은 {{name}}, 어떤 표현이나 행동을 할까요?",
  "잠자리에 들기 전에 {{name}}이(가) 꼭 하던 행동이 있었나요?",
  "{{name}}이(가) 나를 깨울 때 어떻게 했나요?",
  "{{name}}이(가) 갑자기 사라졌다! 우리 친구는 어디에 숨어 있었나요?",

  // #성격과 특징 (7)
  "내 {{name}}만의 특별한 성격이나 특징은 무엇인가요?",
  "잘난 우리 친구의 얼굴에서 가장 귀여운 부분을 자랑해주세요!",
  "내 {{name}}은(는) 내향vs외향? 그리고 그렇게 생각한 이유는 무엇인가요?",
  "{{name}}은(는) 기분이 좋을 때, 어떤 행동으로 표현했나요?",
  "{{name}}은(는) 화가 나거나 심통이 났을 때는 어떻게 표현했나요?",
  "{{name}}만의 특별한 습관이나 버릇은 무엇인가요?",
  "{{name}}은(는) 하루 중 어느 시간대를 가장 좋아했나요? 그 이유는 무엇인가요?",

  // #애정표현과 교감 (5)
  "{{name}}은(는) 나에게 어떤 방식으로 애정을 표현했나요?",
  "내가 {{name}}을(를) 쓰다듬을 때, 가장 좋아했던 부위는 어디였나요?",
  "{{name}}이(가) 나를 위로해준 순간이 있었나요?",
  "사랑스러운 우리 친구의 생일! 특별히 준비하거나 해준 일들이 있나요?",
  "{{name}}와(과) 함께 있으면 자연스럽게 하게 되는 행동이 있었나요?",

  // #특별한 순간 (5)
  "{{name}}와(과) 가장 행복했던 순간을 하나 꼽는다면 언제인가요?",
  "{{name}}이(가) 내게 특별한 선물을 주었던 적이 있나요?",
  "지금 당장 떠오르는 {{name}}와(과)의 추억을 소개해주세요!",
  "사춘기 시절 우리 친구가 피웠던 가장 큰 말썽은 무엇인가요?",
  "가장 잘 나온 {{name}}의 사진을 자랑해주세요!",

  // #우리만의 소통 방법 (5)
  "{{name}}은(는) 어떤 방식으로 나에게 말을 걸었나요?",
  "내가 {{name}}을(를) 부를 때, 어떤 반응을 보였나요?",
  "{{name}}와(과) 내가 꼭 같이 하는 일들은 어떤 게 있었나요?",
  "{{name}}이(가) 내 기분을 먼저 알아차린 적이 있었나요?",
  "우리 친구가 삐졌어요! 삐진 {{name}}을(를) 풀어주는 당신만의 비법이 있나요?",

  // #마무리 질문들 (8)
  "{{name}}와(과) 함께했던 순간 중 가장 소중했던 장면은 무엇인가요?",
  "{{name}}와(과) 함께한 날들 중, 다시 한번 돌아가고 싶은 하루가 있다면 언제인가요?",
  "언젠가 다시 만난다면, 가장 먼저 해주고 싶은 말은 무엇인가요?",
  "{{name}}이(가) 나를 어떤 사람으로 기억했으면 하나요?",
  "{{name}}와(과) 함께하기 전과 후, 내 자신이 달라진 점은 무엇인가요?",
  "{{name}}이(가) 내게 가르쳐준 가장 소중한 것은 무엇인가요?",
  "{{name}}와(과) 함께한 시간을 한 마디로 표현한다면?",
  "마지막으로 {{name}}에게 전하고 싶은 말은 무엇인가요?",
];

export const QUESTIONS_EN = [
  "On the day we first met, how did we become a family?",
  "What is the meaning behind the name '{{name}}'?",
  "When {{name}} first came home, what were they like?",
  "On our first night together, where did {{name}} fall asleep?",
  "When you first gave {{name}} a bath, how did they react?",
  "When you woke up in the morning, what was {{name}} usually doing?",
  "When you returned home from going out, how did {{name}} usually react?",
  "Where was {{name}}’s favorite place?",
  "What was {{name}}’s favorite toy or game?",
  "What kind of treat did {{name}} like the most?",
  "Was there a moment when {{name}} surprised you?",
  "Was there a moment that was so funny because of {{name}}?",
  "Was there a time {{name}} got into trouble and left you in a tough situation?",
  "Was there a moment when {{name}} moved you unexpectedly?",
  "If there’s a person or character {{name}} really liked, please introduce them!",
  "When {{name}} wants a tasty treat, what gestures or expressions do they show?",
  "Before going to sleep, did {{name}} have a routine they always did?",
  "How did {{name}} wake you up?",
  "{{name}} suddenly disappeared! Where was our friend hiding?",
  "What is special about {{name}}’s personality or traits?",
  "Please boast about the cutest part of our proud friend’s face!",
  "Is my {{name}} introverted or extroverted? And why do you think so?",
  "When {{name}} was in a good mood, how did they express it?",
  "When {{name}} was upset or angry, how did they show it?",
  "What unique habits or quirks does {{name}} have?",
  "Which time of day did {{name}} like the most, and why?",
  "How did {{name}} show affection toward you?",
  "When I petted {{name}}, which area did they like the most?",
  "Was there a moment when {{name}} comforted you?",
  "It’s our lovely friend’s birthday! Did you do anything special to celebrate?",
  "When you’re with {{name}}, was there something you found yourself naturally doing?",
  "If you had to pick one moment that was the happiest with {{name}}, when was it?",
  "Has {{name}} ever given you a special gift?",
  "Please share a memory with {{name}} that comes to mind right now!",
  "What was the biggest trouble our friend caused during their adolescent phase?",
  "Show off the best photo you have of {{name}}!",
  "How did {{name}} communicate or 'talk' to you?",
  "When I called {{name}}, how did they respond?",
  "What are some things that you and {{name}} always did together?",
  "Has {{name}} ever noticed your feelings before you said anything?",
  "Our friend is sulking! Do you have a special way of cheering up a sulking {{name}}?",
  "Among your moments with {{name}}, which scene is the most precious?",
  "Of all the days you spent with {{name}}, if there’s one day you’d like to revisit, when would that be?",
  "If you ever meet again someday, what’s the first thing you’d want to say?",
  "What kind of person would you like {{name}} to remember you as?",
  "What has changed about you before and after being with {{name}}?",
  "What is the most precious thing {{name}} taught you?",
  "If you had to describe the time you spent with {{name}} in one word, what would it be?",
  "Finally, what is the last thing you want to say to {{name}}?",
];

export const QUESTIONS_ZH = [
  "初次见面的那一天，我们是如何成为家人的呢？",
  "「{{name}}」这个名字有什么含义？",
  "第一次到家时，{{name}}表现得怎么样？",
  "第一次一起过夜时，{{name}}是在哪里睡着的？",
  "第一次给{{name}}洗澡时，它的反应如何？",
  "早上起床时，{{name}}通常在做什么？",
  "外出回来时，{{name}}通常会有什么反应？",
  "{{name}}最喜欢的地方是哪里？",
  "{{name}}最喜欢的玩具或游戏是什么？",
  "{{name}}最喜欢什么零食？",
  "有过{{name}}让你吃惊的时刻吗？",
  "有因为{{name}}而让你捧腹大笑的瞬间吗？",
  "{{name}}闯祸让你感到尴尬的瞬间有吗？",
  "有{{name}}带给你意想不到感动的时刻吗？",
  "如果有{{name}}非常喜欢的周围人或角色，请介绍一下！",
  "想吃好吃的零食时，{{name}}会做出什么表现或动作？",
  "睡觉前，{{name}}一定会做的事情有哪些？",
  "{{name}}是怎么叫醒你的？",
  "{{name}}突然不见了！它会躲在哪里？",
  "我的{{name}}有哪些特别的性格或特点？",
  "请夸耀一下我们这位朋友脸上最可爱的部分吧！",
  "我的{{name}}是内向还是外向？为什么这样认为？",
  "{{name}}心情好时，会用什么方式来表达？",
  "{{name}}生气或者闹情绪时，会怎么表现？",
  "{{name}}独有的习惯或癖好是什么？",
  "{{name}}一天中最喜欢哪个时间段？为什么？",
  "{{name}}会以什么方式向你表达爱意？",
  "当我抚摸{{name}}时，它最喜欢哪里？",
  "有{{name}}安慰你的瞬间吗？",
  "在{{name}}可爱的生日这天，你有没有做些什么特别的事？",
  "和{{name}}在一起时，你会不自觉地做什么？",
  "如果要选一次与你的{{name}}在一起最幸福的瞬间，那是什么时候？",
  "{{name}}曾经送给你特别的礼物吗？",
  "请分享一个此刻立刻浮现在脑海中的与{{name}}的回忆！",
  "青春期时，我们的朋友闯过的最大祸是什么？",
  "请炫耀一下{{name}}拍得最好的一张照片！",
  "{{name}}通常通过什么方式来和你“对话”？",
  "当你呼唤{{name}}时，它会有什么反应？",
  "和{{name}}一定会一起做的事情有哪些？",
  "{{name}}有没有先于你开口就察觉到你情绪的时刻？",
  "我们的朋友闹情绪了！你哄好闹别扭的{{name}}有什么妙招吗？",
  "与{{name}}相处的时光中，最珍贵的画面是什么？",
  "在和{{name}}一起的日子里，如果有一天想再回去，那是哪一天？",
  "如果有一天再次见面，你最想对{{name}}说的话是什么？",
  "你希望{{name}}记得你是一个怎样的人？",
  "在和{{name}}一起之前和之后，你自身有什么变化？",
  "{{name}}教给你最珍贵的是什么？",
  "如果要用一句话来形容和{{name}}一起的时光，会是什么？",
  "最后，你想对{{name}}说的话是什么？",
];

export const QUESTIONS_JA = [
  "初めて出会った日、私たちはどのように家族になったのですか？",
  "「{{name}}」という名前にはどんな意味がありますか？",
  "初めて家に来た時、{{name}}はどんな様子でしたか？",
  "初めて一緒に過ごした夜、{{name}}はどこで寝ていましたか？",
  "初めて{{name}}を洗ったとき、どんな反応をしましたか？",
  "朝起きたとき、{{name}}は普段何をしていましたか？",
  "外出から戻ったとき、{{name}}は普段どんな反応をしていましたか？",
  "{{name}}が一番好きだった場所はどこですか？",
  "{{name}}が一番好きだったおもちゃや遊びは何ですか？",
  "{{name}}はどんなおやつが一番好きでしたか？",
  "{{name}}があなたを驚かせた瞬間はありましたか？",
  "{{name}}のせいでとても笑った瞬間はありましたか？",
  "{{name}}がいたずらをして困った瞬間はありましたか？",
  "{{name}}が思いがけない感動を与えてくれた瞬間はありましたか？",
  "{{name}}が好きだった周りの人やキャラクターがいれば教えてください！",
  "おいしいおやつが欲しいとき、{{name}}はどんな表情や行動をしますか？",
  "寝る前に{{name}}が必ずしていたことはありましたか？",
  "{{name}}はあなたをどのように起こしていましたか？",
  "{{name}}が突然いなくなった！どこに隠れていたのですか？",
  "私の{{name}}にしかない特別な性格や特徴は何ですか？",
  "自慢のうちの子の顔で、一番かわいい部分を教えてください！",
  "私の{{name}}は内向的？外向的？そう思う理由は何ですか？",
  "{{name}}は機嫌がいいとき、どんな行動で表現していましたか？",
  "{{name}}が怒ったりすねたりしたときは、どのように表現しましたか？",
  "{{name}}だけの特別な習慣やクセは何ですか？",
  "{{name}}は1日のうちどの時間帯が好きでしたか？その理由は？",
  "{{name}}はどのように愛情を表現していましたか？",
  "私が{{name}}をなでるとき、どこをなでられるのが一番好きでしたか？",
  "{{name}}があなたを慰めてくれた瞬間はありましたか？",
  "愛らしい私たちの友達の誕生日！特別に用意したことやしてあげたことはありますか？",
  "{{name}}と一緒にいるとき、自然にしてしまう行動はありますか？",
  "{{name}}と一番幸せだった瞬間を一つ挙げるとしたら、いつですか？",
  "{{name}}があなたに特別なプレゼントをくれたことはありますか？",
  "今すぐ思い浮かぶ{{name}}との思い出を教えてください！",
  "思春期の頃、うちの子が起こした一番大きないたずらは何ですか？",
  "一番よく撮れた{{name}}の写真を自慢してください！",
  "{{name}}はどんな方法であなたに話しかけてきましたか？",
  "あなたが{{name}}を呼んだとき、どんな反応を見せましたか？",
  "{{name}}とあなたが必ず一緒にすることは何ですか？",
  "{{name}}があなたの気持ちを先に察したことはありましたか？",
  "うちの子がすねています！すねた{{name}}を機嫌直しさせるあなたの秘訣はありますか？",
  "{{name}}と過ごした中で、一番大切だった場面はどれですか？",
  "{{name}}と過ごした日々の中で、もう一度戻りたい日があるとしたらいつですか？",
  "いつかまた会えたなら、最初にどんな言葉をかけたいですか？",
  "{{name}}があなたをどんな人だったと覚えていてほしいですか？",
  "{{name}}と一緒に過ごす前と後で、あなたはどのように変わりましたか？",
  "{{name}}があなたに教えてくれた、一番大切なことは何ですか？",
  "{{name}}と過ごした時間を一言で表すとしたら何ですか？",
  "最後に、{{name}}に伝えたい言葉は何ですか？",
];

export const QUESTIONS_SIZE = 49;

export const QUESTIONS: Record<Locale, string[]> = {
  ko: QUESTIONS_KO,
  en: QUESTIONS_EN,
  ja: QUESTIONS_JA,
  zh: QUESTIONS_ZH,
};
